CC=g++
PATH_HEADER=~/HW20/:./
EXE=server
SRC=server.cpp user.cpp
OBJ=$(SRC:.cpp=.o)

all: $(SRC) $(EXE) clean 

$(EXE): $(OBJ)
	$(CC) $(OBJ) -o $@ -I$(PATH_HEADER) -L/usr/lib/mysql -lmysqlclient

%.o : %.cpp
	$(CC) -c -lstd++fs -std=c++17 $< -o $@

clean:
	rm -rf *.o *.a


